INSERT INTO cognvox.profissao (id, descricao) VALUES
(100, 'Assistente Pedagógico (ARIS)'),
(6, 'Assistente Social'),
(1, 'Ator DI'),
(34, 'Aux. de Escritório'),
(35, 'Aux. de Limpeza'),
(36, 'Balconista'),
(37, 'Cozinheiro'),
(38, 'Embalador'),
(40, 'Estoquista'),
(8, 'Fonoaudióloga'),
(39, 'Garçom'),
(41, 'Office-boy'),
(99, 'Outros'),
(28, 'Pai ou Responsável'),
(2, 'Par Interacional'),
(5, 'Pedagogo'),
(4, 'Professor'),
(3, 'Psicólogo'),
(42, 'Recepcionista'),
(43, 'Repositor'),
(7, 'Terapeuta');