INSERT INTO cognvox.unidade (id, nome_instituicao, cidade, estado, logoinstituicao) VALUES
(23, 'COGNVOX', '', '', ''),
(72, 'Creche Alexandre dos Santos Oliveira', '', '', ''),
(41, 'Creche Denilma Bulhões', '', '', ''),
(85, 'Creche João Trajano dos Santos', '', '', ''),
(42, 'Creche Lúcia Nogueira', '', '', ''),
(74, 'Creche Maria Zenaide Rocha Santos', '', '', ''),
(58, 'Creche Menino Jesus', '', '', ''),
(73, 'Creche Professor Manoel Cecílio de Jesus', '', '', ''),
(43, 'Creche Rosete Andrade', '', '', ''),
(44, 'Creche Vovó Judith', '', '', ''),
(86, 'Curso Formação Psicólogos', '', '', ''),
(59, 'Escola Antônio Cândido Toledo', '', '', ''),
(45, 'Escola Barão de Penedo', '', '', ''),
(35, 'Escola Cláudio Daniel Gama Amorim', '', '', ''),
(60, 'Escola Côn. Teotônio Ribeiro', '', '', ''),
(46, 'Escola Dom Constantino Luers', '', '', ''),
(78, 'Escola Eng. Guttemberg Brêda Breda Netto', '', '', ''),
(75, 'Escola Fausto Ferreira Simões', '', '', ''),
(76, 'Escola Francisco Amálio Maria', '', '', ''),
(77, 'Escola Francisco Araújo Azevedo', '', '', ''),
(34, 'Escola General de Góes Monteiro', '', '', ''),
(61, 'Escola Hanna Bertholet', '', '', ''),
(47, 'Escola Irmã Jolenta', '', '', ''),
(62, 'Escola Isabel Cristina Alves Toledo', '', '', ''),
(63, 'Escola João XXIII', '', '', ''),
(48, 'Escola Josef Bergman', '', '', ''),
(79, 'Escola José Buarque da Silva', '', '', ''),
(36, 'Escola José de Carvalho Souza', '', '', ''),
(40, 'Escola Liege Gama Rocha', '', '', ''),
(49, 'Escola Manoel Tavares', '', '', ''),
(64, 'Escola Maria da Glória Pimenteira', '', '', ''),
(81, 'Escola Nossa Sra. do Mont Serrat', '', '', ''),
(65, 'Escola Paulo VI', '', '', ''),
(66, 'Escola Professor Arlindo Ferreira de Moraes', '', '', ''),
(50, 'Escola Professor Douglas Apratto Tenório', '', '', ''),
(67, 'Escola Professor Irênio Araújo', '', '', ''),
(28, 'Escola Professor Pedro Augusto Carneiro Leão', '', '', ''),
(57, 'Escola Professora Helena de O. de Carvalho', '', '', ''),
(37, 'Escola Professora Maria Rocha Santos Silva', '', '', ''),
(51, 'Escola Rotary', '', '', ''),
(82, 'Escola Santa Ana', '', '', ''),
(68, 'Escola Santa Cândida', '', '', ''),
(56, 'Escola Santa Luzia', '', '', ''),
(39, 'Escola Santa Sofia', '', '', ''),
(83, 'Escola Santa Terezinha', '', '', ''),
(69, 'Escola Santo Antônio', '', '', ''),
(70, 'Escola São João Batista', '', '', ''),
(84, 'Escola São Rafael', '', '', ''),
(71, 'ESCOLA TESTE', '', '', ''),
(53, 'Escola Ver. José da Costa Mangabeira', '', '', ''),
(80, 'Escola Ver. José Wilson Melo Nascimento', '', '', ''),
(54, 'Escola Ver. Manoel Soares de Melo', '', '', ''),
(55, 'Escola Wilton Lisboa Lucena', '', '', '');